name: over_the_bike_fit
description: A fitness tracking Flutter app
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/heart.png
    - assets/icons/bike_ui_dark.png
    - assets/splash/splash_screen.png
    - assets/background.png
