name: over_the_bike_fit
description: "A new Flutter project for Bike Heart Rate Monitoring"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 달력 한글화를 위해 추가
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_blue_plus: ^1.31.1
  permission_handler: ^11.3.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0       # 음성 안내 패키지
  table_calendar: ^3.1.0    # 달력 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.13

flutter_native_splash:
  color: "#000000"
  image: "assets/splash/splash_screen.png"
  android_12:
    image: "assets/splash/splash_screen.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/splash/splash_screen.png
