name: over_the_bike_fit
description: Bike Fit Perfect Version
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

# 설정 섹션 (반드시 좌측 끝에 붙여야 함)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/splash/splash_screen.png"
  android_12:
    image: "assets/splash/splash_screen.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/splash/splash_screen.png
    - assets/icon/app_icon.png
