name: over_the_bike_fit
description: Premium bike fitness app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1
  flutter_blue_plus: ^1.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/splash/splash_screen.png
    # 아이콘 파일이 확실히 업로드된 후 아래 주석을 푸세요.
    # - assets/icon/app_icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash_screen.png
  android_12:
    image: assets/splash/splash_screen.png
    color: "#000000"
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
