name: over_the_bike_fit
description: A sporty and minimal fitness tracking Flutter app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0" # 최신 빌드 환경을 위해 SDK 버전을 올렸습니다.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 이미지 파일명과 경로를 업로드하신 폴더 구조에 맞게 맞췄습니다.
  assets:
    - assets/background.png
    - assets/icons/heart.png
    - assets/icons/bike_ui_dark.png
    - assets/splash/splash_screen.png
