name: over_the_bike_fit
description: Final Stable Version.
version: 1.0.1+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_blue_plus: ^1.31.1
  fl_chart: ^0.66.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false # iOS 폴더 에러 방지를 위해 false 설정
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
